/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Database;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class editDonation extends javax.swing.JFrame {

    /**
     * Creates new form editDonation
     */
    public editDonation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        name_ = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pMode3 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(204, 0, 51));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EDIT DONATION");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Amount", "Date", "Mode of Payment", "Credit Card"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel14.setText("Name:");

        jButton2.setText("Enter");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel15.setText("Amount:");

        cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel16.setText("Mode of Payment:");

        pMode3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card", "Check" }));
        pMode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMode3ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel17.setText("Credit Card:");

        jButton1.setText("ENTER");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(name_, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel17)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pMode3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(name_, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pMode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int donation_id;
    int donor_id;
    ArrayList idList;
    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        donation_id = (int) idList.get(Table.getSelectedRow());
        
        String query = "Select donor_id from annualfund.donation where donation_id="+donation_id;
        try {
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next())
                donor_id = rs.getInt("donor_id");
            System.out.println(donor_id);
        } catch (SQLException e){}
        
    }//GEN-LAST:event_TableMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
       
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", null);
            stmt = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(editDonation.class.getName()).log(Level.SEVERE, null, ex);
        }
        idList= new ArrayList();
        int size = 0;

        String query = "SELECT donation_id, name, amount, date, mode_payment,credit_card\n" +
        "FROM annualFund.donor join annualfund.donation using (donor_id)"
        +      "\n where is_active=1 and name LIKE '%" + name_.getText() + "%'";

        try {
           
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                size+=1;
                idList.add(rs.getInt("donation_id"));
                String tmpName = rs.getString("name");
                Float tmpAmount = rs.getFloat("amount");
                Date tmpDate = rs.getDate("date");
                String tmpMode = rs.getString("mode_payment");
                String tmpCard = rs.getString("credit_card");
               // if (tmpCard.isEmpty()) tmpCard = "none";
                

                DefaultTableModel model = (DefaultTableModel) Table.getModel();
                model.setRowCount(size);

                Table.setValueAt(tmpName, size-1, 0);
                Table.setValueAt(tmpAmount, size-1, 1);
                Table.setValueAt(tmpDate, size-1, 2);
                Table.setValueAt(tmpMode, size-1, 3);
                Table.setValueAt(tmpCard, size-1, 4);
               
            }
        } catch (SQLException ex1) {
            ex1.getMessage();
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void pMode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMode3ActionPerformed
        
    }//GEN-LAST:event_pMode3ActionPerformed

    private void ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String query ="";
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", null);
            x = null;
            stmt = conn.createStatement();
            conn.setAutoCommit(false);
                if (!amount.getText().isEmpty()){
                    query = "UPDATE annualfund.donation set amount="+Float.valueOf(amount.getText())+" where donation_id="+donation_id;
                    x = conn.prepareStatement(query);
                    x.executeUpdate();
                    System.out.println("adasjf");
                    checkDonorCircle();
                    
                    checkPledge();
                }
                //cash, cc, check
                if (pMode3.getSelectedIndex()==0 || pMode3.getSelectedIndex()==2){
                    query = "UPDATE annualfund.donation set mode_payment='"+pMode3.getSelectedItem()+"',credit_card = null where donation_id="+donation_id;
                    x = conn.prepareStatement(query);
                    x.executeUpdate();
                }
                else if (pMode3.getSelectedIndex()==1){
                    query = "UPDATE annualfund.donation set mode_payment='"+pMode3.getSelectedItem()+"',credit_card ='"+cc.getText()+"' where donation_id="+donation_id;
                    x = conn.prepareStatement(query);
                    x.executeUpdate();
                }
              
            conn.commit();
            JOptionPane.showMessageDialog(this,"Successful");
            this.dispose();
        } catch (SQLException ex){
            try {
                conn.rollback();
                 ex.getMessage();
            } catch (SQLException ex1) {
                Logger.getLogger(editPledge.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked
    public void checkPledge() throws SQLException{
        Float totalA = (float)0.0;
        Float amtPledged = (float) 0.0;
       
        System.out.println("asdjaksdjk");
        String query = "select sum(amount) as sum from annualfund.donation where donor_id=" + donor_id;
        ResultSet rs = stmt.executeQuery(query);
        if (rs.next()) {
            totalA = rs.getFloat("sum");
        }        
        System.out.println(totalA);
        query = "select * from annualfund.pledge where donor_id =" + donor_id;
        
        try {
            rs = stmt.executeQuery(query);
            while (rs.next()){
               
                String q = "";
                Integer id = rs.getInt("pledge_id");
                amtPledged = rs.getFloat("amount");
                System.out.println(totalA + " " +amtPledged);
                if (totalA <  amtPledged) {
                    q = "UPDATE annualfund.pledge SET is_complete = 0 where pledge_id = " + id;
                }
                else if (totalA >= amtPledged) {
                    System.out.println("here");
                    q = "UPDATE annualfund.pledge SET is_complete = 1 where pledge_id = " + id;
                }
                    x = conn.prepareStatement(q);
                    x.executeUpdate();
                    totalA-=amtPledged;
                
            }
        } catch (SQLException e){} 
    }
    
    public String DonorCircle(){
        if (totalDonation >= 50000)
           return "President Circle";
        else if (totalDonation >= 25000 && totalDonation < 50000)
           return "Platinum Circle";
        else if (totalDonation >= 15000 && totalDonation < 25000)
           return "Gold Circle";
        else if (totalDonation >= 10000 && totalDonation < 15000)
           return "Silver Circle";
        else if (totalDonation >= 5000 && totalDonation < 10000)
           return "Bronze Circle";
        else if (totalDonation >= 1000 && totalDonation < 5000)
           return "Copper Circle";
        else if (totalDonation >= 800 && totalDonation < 1000)
           return "Emerald Circle";
        else if (totalDonation >= 600 && totalDonation < 800)
           return "Fluorite Circle";
        else if (totalDonation >= 400 && totalDonation < 600)
            return "Amethyst Circle";
        else if (totalDonation >= 100 && totalDonation < 400)
            return "Peridot Circle";
       
       return "null";
    }
    
     float totalDonation;
     public void checkDonorCircle() throws SQLException{
        totalDonation = 0;
        String query = "select sum(amount) as total from annualfund.donation \n"	+	
                        "where donor_id =" + donor_id ;
        ResultSet rs = stmt.executeQuery(query);
        if (rs.next()){
            totalDonation = rs.getFloat("total");
        }
       
        String circle = DonorCircle();
        if (circle == "null" || totalDonation==0){
            query = "UPDATE annualfund.donor\n" +
                "SET circle = null" +
                "\n WHERE donor_id =" + donor_id;
        }
        else {
            query = "UPDATE annualfund.donor\n" +
                    "SET circle = '" +circle+ "'" +
                    "\n WHERE donor_id =" + donor_id;
        }
        x = conn.prepareStatement(query);
        x.executeUpdate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editDonation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField cc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name_;
    private javax.swing.JComboBox pMode;
    private javax.swing.JComboBox pMode1;
    private javax.swing.JComboBox pMode2;
    private javax.swing.JComboBox pMode3;
    // End of variables declaration//GEN-END:variables
    Statement stmt;
    Connection conn;
    PreparedStatement x;
}
