/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;

/**
 *
 * @author johnnyboyromero
 */
public class JokeUI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public JokeUI() {
        initComponents();
        this.setTitle("Beta University Annual Fund");
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        pledges_Panel.setVisible(false);
        donors_Panel.setVisible(true);
        donations_Panel.setVisible(false);

        main_List.setVisible(true);
        main_Reports.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Reports_Label = new javax.swing.JLabel();
        List_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Letter_Label = new javax.swing.JLabel();
        main_Layer = new javax.swing.JLayeredPane();
        main_Reports = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        innnerReports = new javax.swing.JLayeredPane();
        annual_Panel = new javax.swing.JPanel();
        main_List = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        innerList = new javax.swing.JLayeredPane();
        donations_Panel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        addDonations = new javax.swing.JLabel();
        pledges_Panel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        addPledge = new javax.swing.JLabel();
        donors_Panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        deleteDonor = new javax.swing.JLabel();
        editDonor = new javax.swing.JLabel();
        donorsButton = new javax.swing.JLabel();
        pledgesButton = new javax.swing.JLabel();
        donations_Button = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        Reports_Label.setBackground(new java.awt.Color(153, 0, 0));
        Reports_Label.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        Reports_Label.setForeground(new java.awt.Color(255, 255, 255));
        Reports_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reports_Label.setText("Reports");
        Reports_Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Reports_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reports_LabelMouseClicked(evt);
            }
        });

        List_Label.setBackground(new java.awt.Color(153, 0, 0));
        List_Label.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        List_Label.setForeground(new java.awt.Color(255, 255, 255));
        List_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        List_Label.setText("List");
        List_Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        List_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_LabelMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/logo3.png"))); // NOI18N

        Letter_Label.setBackground(new java.awt.Color(153, 0, 0));
        Letter_Label.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        Letter_Label.setForeground(new java.awt.Color(255, 255, 255));
        Letter_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Letter_Label.setText("Letter");
        Letter_Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Letter_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letter_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(List_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reports_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Letter_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(List_Label)
                            .addComponent(Reports_Label)
                            .addComponent(Letter_Label))
                        .addGap(37, 37, 37)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        main_Reports.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/yearLogo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/monthLogo.png"))); // NOI18N

        annual_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout annual_PanelLayout = new javax.swing.GroupLayout(annual_Panel);
        annual_Panel.setLayout(annual_PanelLayout);
        annual_PanelLayout.setHorizontalGroup(
            annual_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        annual_PanelLayout.setVerticalGroup(
            annual_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout innnerReportsLayout = new javax.swing.GroupLayout(innnerReports);
        innnerReports.setLayout(innnerReportsLayout);
        innnerReportsLayout.setHorizontalGroup(
            innnerReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(annual_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        innnerReportsLayout.setVerticalGroup(
            innnerReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innnerReportsLayout.createSequentialGroup()
                .addComponent(annual_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        innnerReports.setLayer(annual_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout main_ReportsLayout = new javax.swing.GroupLayout(main_Reports);
        main_Reports.setLayout(main_ReportsLayout);
        main_ReportsLayout.setHorizontalGroup(
            main_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_ReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(innnerReports)
                .addContainerGap())
        );
        main_ReportsLayout.setVerticalGroup(
            main_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_ReportsLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_ReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(innnerReports)
                .addContainerGap())
        );

        main_List.setBackground(new java.awt.Color(255, 255, 255));
        main_List.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(204, 0, 51));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Donations List");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(362, 362, 362))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        addDonations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/addNew.png"))); // NOI18N
        addDonations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDonationsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout donations_PanelLayout = new javax.swing.GroupLayout(donations_Panel);
        donations_Panel.setLayout(donations_PanelLayout);
        donations_PanelLayout.setHorizontalGroup(
            donations_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(donations_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addDonations))
        );
        donations_PanelLayout.setVerticalGroup(
            donations_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donations_PanelLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addComponent(addDonations))
        );

        jPanel6.setBackground(new java.awt.Color(204, 0, 51));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pledges List");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(362, 362, 362))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        addPledge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/addNew.png"))); // NOI18N
        addPledge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPledgeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pledges_PanelLayout = new javax.swing.GroupLayout(pledges_Panel);
        pledges_Panel.setLayout(pledges_PanelLayout);
        pledges_PanelLayout.setHorizontalGroup(
            pledges_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pledges_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPledge)
                .addContainerGap())
        );
        pledges_PanelLayout.setVerticalGroup(
            pledges_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pledges_PanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 425, Short.MAX_VALUE)
                .addComponent(addPledge))
        );

        donors_Panel.setBackground(new java.awt.Color(204, 204, 204));

        jPanel5.setBackground(new java.awt.Color(204, 0, 51));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Donors List");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jLabel11)
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        deleteDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/delete.png"))); // NOI18N

        editDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/edit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editDonor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteDonor)
                .addGap(23, 23, 23))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteDonor)
                    .addComponent(editDonor))
                .addContainerGap())
        );

        javax.swing.GroupLayout donors_PanelLayout = new javax.swing.GroupLayout(donors_Panel);
        donors_Panel.setLayout(donors_PanelLayout);
        donors_PanelLayout.setHorizontalGroup(
            donors_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        donors_PanelLayout.setVerticalGroup(
            donors_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donors_PanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout innerListLayout = new javax.swing.GroupLayout(innerList);
        innerList.setLayout(innerListLayout);
        innerListLayout.setHorizontalGroup(
            innerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerListLayout.createSequentialGroup()
                .addComponent(donors_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(innerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pledges_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(innerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(donations_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innerListLayout.setVerticalGroup(
            innerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerListLayout.createSequentialGroup()
                .addComponent(donors_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(innerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerListLayout.createSequentialGroup()
                    .addComponent(pledges_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(innerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(donations_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innerList.setLayer(donations_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        innerList.setLayer(pledges_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        innerList.setLayer(donors_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(innerList)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(innerList)
                .addContainerGap())
        );

        donorsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/donors.png"))); // NOI18N
        donorsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donorsButtonMouseClicked(evt);
            }
        });

        pledgesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/pledges.png"))); // NOI18N
        pledgesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pledgesButtonMouseClicked(evt);
            }
        });

        donations_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/donations.png"))); // NOI18N
        donations_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donations_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout main_ListLayout = new javax.swing.GroupLayout(main_List);
        main_List.setLayout(main_ListLayout);
        main_ListLayout.setHorizontalGroup(
            main_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_ListLayout.createSequentialGroup()
                .addGroup(main_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(main_ListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(main_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(main_ListLayout.createSequentialGroup()
                                .addComponent(donations_Button)
                                .addGap(15, 15, 15))
                            .addGroup(main_ListLayout.createSequentialGroup()
                                .addComponent(pledgesButton)
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, main_ListLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(donorsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        main_ListLayout.setVerticalGroup(
            main_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_ListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(main_ListLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(donorsButton)
                .addGap(27, 27, 27)
                .addComponent(pledgesButton)
                .addGap(30, 30, 30)
                .addComponent(donations_Button)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout main_LayerLayout = new javax.swing.GroupLayout(main_Layer);
        main_Layer.setLayout(main_LayerLayout);
        main_LayerLayout.setHorizontalGroup(
            main_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_List, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(main_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(main_Reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        main_LayerLayout.setVerticalGroup(
            main_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_List, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(main_LayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(main_Reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        main_Layer.setLayer(main_Reports, javax.swing.JLayeredPane.DEFAULT_LAYER);
        main_Layer.setLayer(main_List, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Layer)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main_Layer))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pledgesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pledgesButtonMouseClicked
        donors_Panel.setVisible(false);
        pledges_Panel.setVisible(true);
        donations_Panel.setVisible(false);
    }//GEN-LAST:event_pledgesButtonMouseClicked

    private void donorsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donorsButtonMouseClicked
        donors_Panel.setVisible(true);
        pledges_Panel.setVisible(false);
        donations_Panel.setVisible(false);
    }//GEN-LAST:event_donorsButtonMouseClicked

    private void addPledgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPledgeMouseClicked
        System.out.println("yeah");
    }//GEN-LAST:event_addPledgeMouseClicked

    private void addDonationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDonationsMouseClicked

    }//GEN-LAST:event_addDonationsMouseClicked

    private void donations_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donations_ButtonMouseClicked
        donors_Panel.setVisible(false);
        pledges_Panel.setVisible(false);
        donations_Panel.setVisible(true);
    }//GEN-LAST:event_donations_ButtonMouseClicked

    private void List_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_LabelMouseClicked
        main_List.setVisible(true);
        main_Reports.setVisible(false);
    }//GEN-LAST:event_List_LabelMouseClicked

    private void Reports_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reports_LabelMouseClicked
        main_List.setVisible(false);
        main_Reports.setVisible(true);
        
    }//GEN-LAST:event_Reports_LabelMouseClicked

    private void Letter_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letter_LabelMouseClicked
        // TODO add your handling code here:
        addDonor a = new addDonor();
        a.show();
        a.setDefaultCloseOperation(a.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_Letter_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JokeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JokeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JokeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JokeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JokeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Letter_Label;
    private javax.swing.JLabel List_Label;
    private javax.swing.JLabel Reports_Label;
    private javax.swing.JLabel addDonations;
    private javax.swing.JLabel addPledge;
    private javax.swing.JPanel annual_Panel;
    private javax.swing.JLabel deleteDonor;
    private javax.swing.JLabel donations_Button;
    private javax.swing.JPanel donations_Panel;
    private javax.swing.JLabel donorsButton;
    private javax.swing.JPanel donors_Panel;
    private javax.swing.JLabel editDonor;
    private javax.swing.JLayeredPane innerList;
    private javax.swing.JLayeredPane innnerReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLayeredPane main_Layer;
    private javax.swing.JPanel main_List;
    private javax.swing.JPanel main_Reports;
    private javax.swing.JLabel pledgesButton;
    private javax.swing.JPanel pledges_Panel;
    // End of variables declaration//GEN-END:variables
}
